/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->first_num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second_num))
		 return FALSE;
	return TRUE;
}
